// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package framework

import (
	"dreadnought/adapters"
	"dreadnought/cases"
	"dreadnought/framework/networking"
	"dreadnought/framework/strategies"
)

// Injectors from wire.go:

func InitializeApp() App {
	limiterMediator := cases.ProvideLimiterMediator()
	limiterInteractor := cases.ProvideLimiterInteractor(limiterMediator)
	limiterController := adapters.ProvideLimiterController(limiterInteractor)
	httpLimiterServer := networking.ProvideLimiterServer(limiterController)
	strategiesRegistry := strategies.ProvideStrategiesRegistry(limiterMediator)
	app := ProvideApp(httpLimiterServer, strategiesRegistry)
	return app
}
