// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package framework

import (
	"adeptus-limitarius/adapters"
	"adeptus-limitarius/cases"
	"adeptus-limitarius/framework/networking"
)

// Injectors from wire.go:

func InitializeApp() App {
	limiterInteractor := cases.ProvideLimiterInteractor()
	limiterController := adapters.ProvideLimiterController(limiterInteractor)
	httpLimiterServer := networking.ProvideLimiterServer(limiterController)
	app := ProvideApp(httpLimiterServer)
	return app
}
